<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Logging\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-nblumhardt-02322" />
    <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinalidadeEstudo.Application\FinalidadeEstudo.Application.csproj" />
    <ProjectReference Include="..\FinalidadeEstudo.Infrastructure\FinalidadeEstudo.Infrastructure.csproj" />
  </ItemGroup>

</Project>
