name: Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run XUnit tests
        run: dotnet test test/FinalidadeEstudo.XUnit/FinalidadeEstudo.XUnit.csproj --no-build --configuration Release